# Generated by Django 3.1.1 on 2020-09-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=2, null=True)),
                ('age_lower_bound', models.PositiveSmallIntegerField(null=True)),
                ('age_upper_bound', models.PositiveSmallIntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('pay', models.PositiveIntegerField(null=True)),
                ('type_of_pay', models.CharField(max_length=5, null=True)),
                ('worktime_start', models.PositiveSmallIntegerField(null=True)),
                ('worktime_end', models.PositiveSmallIntegerField(null=True)),
                ('alba_site_name', models.CharField(max_length=10, null=True)),
                ('alba_site_number', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
