# Generated by Django 3.1.1 on 2020-09-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alba',
            new_name='AlbaInfo',
        ),
    ]
