# Generated by Django 3.1.1 on 2020-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20200924_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='albainfo',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
