# Generated by Django 3.0.6 on 2020-05-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_alba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alba',
            name='age_lower_bound',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alba',
            name='age_upper_bound',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alba',
            name='sex',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='alba',
            name='type_of_pay',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='alba',
            name='worktime_end',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alba',
            name='worktime_start',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alba',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
