# Generated by Django 3.0.6 on 2020-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_alba', '0003_alba_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='alba',
            name='alba_site_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alba',
            name='alba_site_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
